### ISSUE TITLE
UDP connection

### ISSUE THREAD

**Issue by docHell** [kvenux/nodegcs#4]
Hi, I'm trying to rewrite your project using dgram library instead of "net" to control a px4 drone using udp connection.
I'm able to read but there is a problem sending commands.
This is the error I've got.
"WARN [mavlink] ignoring CMD with same SYS/COMP (1/1)"

Basically this is a takeoff.

` mav_parser.createMessage("COMMAND_LONG", {
    "param1": param1,
    "param2": param2,
    "param3": param3,
    "param4": param4,
    "param5": param5,
    "param6": param6,
    "param7": param7,
    "command": command,
    "target_system":1,
    "target_component": 1,
    "confirmation": confirmation
  },
    function (message) {

      LOG("------------------------------------------------")
      LOG(message.toString());
 
   
      mav_port_receive.send(message.buffer, 0, message.buffer.length, PORT, HOST, function(err, bytes) {
        if (err)  {
          LOG(err)
        }

        LOG("--CALL BACK PARTITA-")
        LOG("-e > " +err)
       
        // mav_port_send.close();
        
      });
     
      return;
    });
}`
LOG is a logger.
mav_port_receive is the same of your map_port.

`mav_port_receive = dgram.createSocket("udp4")
   LOG("LISTENER  PORT : " + connection_port +", ADDRESS : " +connection_path)
   mav_port_receive.bind( connection_port,connection_path);`

and it works pretty well as a listerner

`mav_port_receive.on("message", (msg, rinfo) => {
       
      if(msg[0]!= 0 && msg[1]!= 7){
        var radio_status = {
          rssi: parseInt(msg[2]),
        };
      } 
      mav_parser.parse(msg);
      
  
    });
 `

Have you any solution or suggestion ?

**Comment by kvenux** [comment]
This repo is built as an interface with ardupilot. To support px4, you may need to make some adjustments.

According to px4 mavlink receiver(Firmware/src/modules/mavlink/mavlink_receiver.cpp):

`if (msg->sysid == mavlink_system.sysid && msg->compid == mavlink_system.compid) {
			PX4_WARN("ignoring CMD with same SYS/COMP (%d/%d) ID", mavlink_system.sysid, mavlink_system.compid);
			return;
		}`

You can refer to px4 mavlink configuration to set proper SYS and COMP when sending CMD message.

**Comment by kvenux** [comment]
@docHell Based on my experience, to set up a px4 interface, you need following steps:
1. Sending correct heartbeat package. Set up clear reconnection logic.
2. Decoding all msgs. This can be easy.
3. Set package frequency.
4. Sending correct CMD. 

You can refer to message interface of any px4 based ground control station.

**Comment by docHell** [comment]
I suppose the problem is also in the mavlink library.
Due to the fact that the mavlink lib is not compatible with "electron" and "Angular", I've modified it to fix the problem and so I've noticed that by default it parses only  "common" and "ardupilotmega" xml.

**Comment by kvenux** [comment]
Exactly, you need to configure xml files as well.
This lib is compatible with electron. You can use event emitter as the backends.

**Comment by docHell** [comment]
This lib is compatible, but not mavlink.
But I've totally changed it using rxjs and promise instead.
Now, I'm using the px4.xml but, I've still the same problem.

**Comment by docHell** [comment]
This lib is compatible, but not mavlink.
But I've totally changed it using rxjs and promise instead.
Now, I'm using the px4.xml but, I've still the same problem.
